((nil . ((cider-clojure-cli-aliases . "-A:dev")
         (cider-default-cljs-repl . shadow)
         (cider-shadow-default-options . ":app")
         (cider-shadow-watched-builds . (":app"))
         (cider-offer-to-open-cljs-app-in-browser . nil))))
